### ISSUE TITLE
Django 5.* compatability

### ISSUE THREAD

**Issue by robertvy** [danihodovic/django-webhook#27]
Are there any plans to support Django 5.*?

**Comment by danihodovic** [comment]
I think all we have to do is update the dependency requirement here: https://github.com/danihodovic/django-webhook/blob/master/pyproject.toml#L29

**Comment by robertvy** [comment]
Hi @danihodovic,

Thank you for the quick response.

I added the django_webhook app to my Django 5 project manually, and webhooks are working when following the docs. So, I think you are correct that simply updating the poetry dependency should suffice.

Would you like me to open a PR to update the pyproject.toml file accordingly?

**Comment by danihodovic** [comment]
Yes let's do that

**Comment by robertvy** [comment]
I have created a pull request to update the Django dependency.
